spring:
  messages:
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false

logging:
  level:
    ROOT: ERROR